### ISSUE TITLE
user0の挙動の変更要望

### ISSUE THREAD

**Issue by geotrader** [crftwr/keyhac-win#10]
無変換にuser0を割り当てて無変換単独をF7に割り当ててキー操作を行っております.
Uなどの通常のキーをおした後にuser0キーを押した場合にU0-Uとして解釈されてしまい,U0直前に押下したキーがすり抜けてしまいます.

具体的な弊害としては"グローバリゼーション"と打っているのに"ぐろーばりぜーしょn"となることが有り,非常にタイプミスが多くなってしまいます.

無変換キーがすり抜けないのは非常に感動しておりますが,この問題は高速でタイピングを行おうとした際に致命的なので修正願いたいです.
よろしくお願いします.

---

IN  : D-M
TRU : D-M
IN  : U-M
TRU : U-M
IN  : O-M
IN  : D-A
TRU : D-A
IN  : U-A
TRU : U-A
IN  : O-A
IN  : D-K
TRU : D-K
IN  : U-K
TRU : U-K
IN  : O-K
IN  : D-K
TRU : D-K
IN  : U-K
TRU : U-K
IN  : O-K
IN  : D-U
TRU : D-U
IN  : D-(29)
IN  : U-LU0-U
TRU : U-LU0-U
IN  : U-(29)

**Comment by crftwr** [comment]
レポートをありがとうございます。

これは、Uがすり抜けているというよりは、

Down-U
Down-(29)
Up-U
Up-(29)

という順番で入力したときに、Oneshot-(29) に割り当てた F7 が発動しないという問題でしょうか？

**Comment by crftwr** [comment]
対処してみました。これでいかがでしょうか？
(KeyUpイベントでは、ワンショットモディファイアをキャンセルしないようにしました。)

http://crftwr.github.io/keyhac/download/keyhac_173.zip

**Comment by geotrader** [comment]
問題が起きなくなりました.本当にありがとうございます!
これでAHKを(半分)捨ててkeyhacに乗り換えられます!!!
