### ISSUE TITLE
マウスのボタンをクリックする機能の要望

### ISSUE THREAD

**Issue by subak** [crftwr/keyhac-win#11]
モディフィアキーを押しながらマウスのボタンをクリックする機能があると嬉しいです。
例えばShift+左ボタンが使えるようになるとエクスプローラなどで複数のファイルを選択することができるようになります。

**Comment by crftwr** [comment]
キーボードの入力で、疑似的にマウスボタンの操作イベントを生成するということでしょうか？

たとえば、
global_keymap["F1"] = "Shift-LButton"
のようなことでしょうか？

**Comment by subak** [comment]
はい、キーボードの入力で擬似的にマウスボタンの操作イベントを生成したいです。

クリックするだけであれば
global_keymap["F1"] = keymap.MouseButtonClickCommand("left")
というようにすれば可能と思いますが、この時にモディファイアキーを押しながら左クリックというようなことができると嬉しいです。

**Comment by crftwr** [comment]
Shift-LButton が作用するのは、現在のマウスカーソル位置になるのですが、そんなイメージでしょうか？
つまり、事前にマウスカーソルは、移動させておく必要があります。

**Comment by subak** [comment]
はい、そのイメージです。
例えばエクスプローラなどでファイルを選択する場合に、一つ目のファイルをクリックして選択します。その後カーソルを動かし別のファイルを選択する時にShiftを押しながらクリックすることによって複数のファイルを選択可能になります。

カーソルの移動はMouseMoveCommandでできるので、モディファイアキーを押しながら左クリックというような指定ができると、上記の操作が全てキーボードだけで可能になり嬉しいです。

**Comment by crftwr** [comment]
ご説明をありがとうございます。
追加できるはずの機能ですので、今後の機能追加で対応しようと思います。

**Comment by crftwr** [comment]
遅くなりましたが実装しました。次のバージョンから入りますが、
もしお時間あれば、下のパッケージでお試しください。

Keyhac ver 1.75 beta 1
http://crftwr.github.io/keyhac/download/keyhac_175_b1.zip

Closeします。
