### ISSUE TITLE
user0単独に操作割当環境でのキーボードマクロ記録

### ISSUE THREAD

**Issue by geotrader** [crftwr/keyhac-win#12]
以下の状況下で

---

user0単独ににF7を割当
user0-Jに下移動を割当

---

以下の動作をすると

---

user0-1でキーボードマクロを開始
user0-Jで下移動
user0-2でキーボードマクロを終了
user0-3でキーボードマクロを再生

---

user0-Jに加えてuser0単独であるF7も発動してしまうようです.

---

IN  : D-(29)
IN  : D-LU0-J
OUT : [Key(40)]
IN  : U-LU0-J
TRU : U-LU0-J
IN  : O-LU0-J
OUT : [KeyUp(74)]
IN  : U-(29)
IN  : U-LU0-3
TRU : U-LU0-3
IN  : U-(29)

**Comment by crftwr** [comment]
レポートをありがとうございます。
確かに再現します。調査いたします。

**Comment by crftwr** [comment]
手元の最新の環境で確認したのですが、再現しません。
Closeいたしますが、まだ再現するということでしたら、Reopenをお願いします。

**Comment by geotrader** [comment]
最新Verで解決していたようです。
Closeありがとうございます。
