### ISSUE TITLE
マルチストロークの定義の入力途中でマウス操作が入ったら、それまでの入力をキャンセルしたい

### ISSUE THREAD

**Issue by tomoemon** [crftwr/keyhac-win#13]
いつも便利に使わせていただいております。

今実現したい定義は「左の Ctrl キーを2回連続で押したらメモ帳を起動する」といったものなのですが、これ自体は下記の定義で実現できています。

``` py
key = "O-LCtrl"
target_map = keymap.defineWindowKeymap()
target_map[key] = keymap.defineMultiStrokeKeymap(key)
target_map[key][key] = lambda x=0: print("run notepad")
```

ただ、Ctrl キーはマウスのスクロールキーとともに「拡大・縮小」のために使うことも多く、
1. LCtrl キーを押しながらマウススクロールで拡大
2. （大きくなりすぎたので）LCtrl キーを押しながらマウススクロールで縮小

といった操作をすることもよくあります。
そして、この場合に上記定義によってメモ帳が起動してしまいます。
途中でマウス操作が入ったらキー入力をキャンセルできれば良いのですが、config レベルでそれを制御する方法があれば教えていただきたいです。

**Comment by crftwr** [comment]
Configでは現状難しいです。

Mouseのボタンの押し込み時は、ワンショットモディファイアキーのキャンセルを行いますが、
ホイールの操作のときにはやっていません。

対応しておきます。

**Comment by crftwr** [comment]
マウスのボタンとホイールが操作されたときに、ワンショットモディファイアキーのキャンセルを行うように変更しました。次回のリリース (1.73-) から有効になります。

**Comment by tomoemon** [comment]
ありがとうございます！次回のリリース楽しみにしています。
