### ISSUE TITLE
モディファイアキー+ファンクションキーの動作の不具合

### ISSUE THREAD

**Issue by geotrader** [crftwr/keyhac-win#14]
ファイル検索ソフト上で右クリックをしたいの下記の設定してます．

---

keymap_global["U0-R"] = "S-F10"

---

単純にF10キーを押したときと同じような動作をしてしまいます．

---

IN  : D-(29)
IN  : D-LU0-R
OUT : [KeyDown(160), Key(121), KeyUp(160)]
IN  : U-LU0-R
TRU : U-LU0-R
IN  : O-LU0-R
IN  : U-(29)

**Comment by crftwr** [comment]
Chrome と Explorerで試したのですが、
手元はで再現しないようでした。(Win10)

そちらでは、どういった環境でしょうか？

**Comment by geotrader** [comment]
すみません.
別キーフックソフトが干渉しているようでした.

失礼しました.

**Comment by geotrader** [comment]
ちなみにファイル検索のeverythingx64との競合でした.
そちらのキーフックと競合しているのか,F10がすり抜けてしまうようでした.

実は他のソフトでも同じような症状を抱えてまして..
難しくなければcfilerのように管理者権限で起動出来るようにして頂けると助かります.
