### ISSUE TITLE
通知領域からのkeyhacのアイコン消失バグの報告

### ISSUE THREAD

**Issue by geotrader** [crftwr/keyhac-win#16]
## 現象

explorerクラッシュで通知領域からkeyhacアイコンが消える。
(機能の動作には問題ないが、configの編集などに支障がある。)
## 回避方法

タスクマネージャーからkeyhac.exeのタスクを終了して再開すれば、通知アイコンが表示され正常に起動する。
## 環境
- Win10(x64)
- マルチディスプレイ
## 手順
1. タスクマネージャーからexplorerのタスクの終了
2. タスクマネージャーメニューのファイルからタスクの実行でexplorer.exeを再起動
3. 通知領域からkeyhacのアイコンが消えている。
## 再現率

3/3

**Comment by crftwr** [comment]
レポートをありがとうございます。
対応が遅くなりましたが、 ver 1.76 で修正しました。Closeします。
