### ISSUE TITLE
Mac版にて設定ファイルの読み込みで読み込めず再起動が必要になる

### ISSUE THREAD

**Issue by bonk** [crftwr/keyhac-win#23]
Mac版でGUI、スクリプトの両方ためしてみたのですが、
設定ファイルの読み込みをすると機能しなくなり
再起動が必要になるように思いましたのでご報告までです。（OS:Sierra）
例えば、スクリプトから自身を再起動させる方法などありますでしょうか。

**Comment by crftwr** [comment]
bonkさん、レポートをありがとうございます。
確認いたします。

エラーメッセージなどは出ておりますでしょうか？
機能しなくなる、というのは、キーのカスタマイズがされない、という意味でしょうか？

**Comment by bonk** [comment]
お世話になります。

そうです。キーのカスタマイズが向こうになるという意味でした。
エラーは出ておらず、読み込みしましたとコンソールログが記載されます。

しかし、こちらですが再現させてみたところ理屈がわかったように思います。
エディタやブラウザなど編集しているアプリを
切り替えるとカスタマイズが復帰していました。
（時間遅延ではないようです）
なぜカレントのアプリで有効にならないかわからないのですが、
当方としては、ひとまず大丈夫です。
