### ISSUE TITLE
継承について

### ISSUE THREAD

**Issue by ghost** [crftwr/keyhac-win#3]
下記のようなconfig.pyにて
def_execのような実行をしたいのですが
可能でしょうか？
???の箇所に何を渡していいかがわかりません

def configure(keymap):

```
def mouse_wheel_up():
    keymap.command_MouseWheel(2)()

def mouse_wheel_down():
    keymap.command_MouseWheel(-2)()

def def_exec(def_name):
    obj = ???
    getattr(obj, def_name)()

def_exec('def mouse_wheel_up')
```

**Comment by crftwr** [comment]
とくに、Keyhacに固有のテクニックではありませんが、getattr で文字列によって実行するオブジェクトを切り替えるには、たとえば下記のようにします。

``` python
class Klass:
         :
   def mouse_wheel_up(self):
      keymap.command_MouseWheel(2)()

   def mouse_wheel_down(self):
       keymap.command_MouseWheel(-2)()

   def def_exec(self,def_name):
      getattr(self, def_name)()
         :

k = Klass()
k.def_exec("mouse_wheel_up")
```

**Comment by tarotarotarotaro** [comment]
def configure(keymap):
の中に

def mouse_wheel_up():
を定義しているので

k = Keymap()
k.def_exec("mouse_wheel_up")
をconfig.pyに書くと
下記のようなエラーが発生します

AttributeError: 'Keymap' object has no attribute 'def_exec'


classをconfig.pyにあらたに定義すれば問題ないのですが、、、
その場合

class macro():
    def mouse_wheel_up():
        keymap.command_MouseWheel(2)()

と定義するとまた別のエラーになります

**Comment by ghost** [comment]
def configure(keymap):
の中に

def mouse_wheel_up():
を定義しているので

k = Keymap()
k.def_exec("mouse_wheel_up")
をconfig.pyに書くと
下記のようなエラーが発生します

AttributeError: 'Keymap' object has no attribute 'def_exec'

classをconfig.pyにあらたに定義すれば問題ないのですが、、、
その場合

class macro():
def mouse_wheel_up():
keymap.command_MouseWheel(2)()

と定義するとまた別のエラーになります

**Comment by ghost** [comment]
k = Keymap()
ここをどうしていいかがわかりません
