### ISSUE TITLE
Mouse Without Borders からのイベント

### ISSUE THREAD

**Issue by yosagi** [crftwr/keyhac-win#4]
Mouse Without Borders (https://www.microsoft.com/en-us/download/details.aspx?id=35460) を使って複数のPCを1つのキーボードで操作しています。keyhac は Injected Event をほぼすべて無視してしまうので、Mouse Without Bordersからのキーイベントを処理できません。何か対策できませんでしょうか。

**Comment by crftwr** [comment]
他のプログラムでinjectされたキーイベントを無視しないように、タイムスタンプもチェックするようにしてみます。

**Comment by crftwr** [comment]
このビルドでどうでしょうか？
http://crftwr.github.io/keyhac/download/keyhac_172_beta1.zip

申し訳ありませんが、治っているかどうか、あまりテストできていません。

**Comment by crftwr** [comment]
タイムスタンプのチェックだと、Mouse Without Borders からキーの同時押しのイベントが来た時に、片方を無視してしまいそうです。もうちょっと見直す必要がありそうです。

**Comment by crftwr** [comment]
自分自身でInjectしたイベント以外は、無視せずに処理するようにしてみました。
ver 1.72 としてリリースしました。

http://craftwave.blogspot.jp/2016/01/keyhac-for-windows-ver-172.html

まだ動きがおかしいようでしたら、Reopenをお願いします。

**Comment by yosagi** [comment]
1.72で期待通り動きそうです。対応ありがとうございました。
リモートデスクトップの一つ Mirror DTC も使っていますが、こちらも通るようになったようです。

**Comment by crftwr** [comment]
ご確認ありがとうございます。
動いたようでよかったです。
