### ISSUE TITLE
プロジェクト全体のライセンス

### ISSUE THREAD

**Issue by takaxp** [crftwr/keyhac-win#43]
本プロジェクトは，comtypes, Python Imaging Library, Python についてはライセンスが明示されておりますが，それ以外についてはライセンス明示無しの状態という理解でよいでしょうか？

**Comment by crftwr** [comment]
遅くなりましたが、MIT ライセンスである旨、明記しました。
https://github.com/crftwr/keyhac/blob/master/LICENSE
