### ISSUE TITLE
複数のキーマップで同じマルチストロークキーに結びつくキーを定義したい

### ISSUE THREAD

**Issue by smzht** [crftwr/keyhac-win#45]
Keyhac ではマルチストロークキーの定義ができますが、同じマルチストロールキーを複数のキーマップで定義した場合、そのひとつ（恐らく最後に定義したキーマップ）上でしか、そのマルチストロークキーと結びつけるキーの定義が有効になりません。

たとえば、２つのキーマップを定義し、そのどちらのキーマップにも C-x をマルチストロークキーとして定義した場合、C-x と結びつけるキー（２番めのキー）が異なるものであっても、片側のキーマップでマルチストロークキーと結びつけたキーは全て無効となります。

同じマルチストロークキーでも結びつけるキーが異なるものである場合には複数のキーマップで定義できるようにしたいのですが、対応可能でしょうか？

ご検討をお願いいたします。

**Comment by smzht** [comment]
本件、私の認識誤りだったようです。

同じマルチストロールキーを複数のキーマップで定義することができましたので、本件closeとさせていただきます。

**Comment by smzht** [comment]
上記は定義した複数のキーマップが、あるアプリで同時に有効になっている場合に発生する現象です。
キーマップが排他的に切り替わる状況の場合には問題なく動作します。

以上、よろしくお願いします。

**Comment by crftwr** [comment]
ご指摘の通り、現状だと、複数のWindowKeymapに該当する場合、前に定義したWindowKeymapのキーは、後に定義したWindowKeymapのキーによって上書きされます。そして、マルチストロークに入るためのキーも同様に上書きされます。

やや強引ですが、defineMultiStrokeKeymap() から返ってくる WindowKeymap を複数のウインドウ種別で共有して使って、WindowKeymap.applying_func を使って動的に WindowKeymap.keymap を更新するという方法があり得ます。(動作未確認)

この方法が解決にならない場合、ほかに良い解決方法がないか検討します。

**Comment by smzht** [comment]
ご回答いただき、ありがとうございます。

WindowKeymap.applying_func という機能があるのですね。この機能を使うと対策できそうな気がします。検討してみます。

**Comment by smzht** [comment]
WindowKeymap.applying_func を使って、マルチストロークのキーマップ毎に次のような処理を行うことで対策できました。
```
window_keymap1.keymap = {**window_keymap2.keymap, **window_keymap1.keymap}
```
ついては、本件クローズさせていただきます。アドバイスありがとうございました。
