### ISSUE TITLE
Win+RShift のモディファイアキーが正常に動作しない

### ISSUE THREAD

**Issue by smzht** [crftwr/keyhac-win#48]
次のような config.py を設定した際、Win+LShift+m では動作するのですが、Win+RShift+m では動作しません（Win+m の後のウィンドウのリストアが後者の場合動作しません）。

もし対策があれば、検討いただければ幸いです。よろしくお願いします。

~~~python
import keyhac_keymap
from keyhac import *

def configure(keymap):
    keymap_global = keymap.defineWindowKeymap()
    keymap_global["W-S-m"] = "W-S-m"
~~~

**Comment by crftwr** [comment]
@smzht さん、レポートをありがとうございます。

この症状が起きる原因はわかりませんが、下記のようにすれば回避できるようです。

    keymap_global["W-LS-m"] = "W-LS-m"
    keymap_global["W-RS-m"] = "W-RS-m"

**Comment by smzht** [comment]
ご回答ありがとうございます。

L、Rを直接指定すると動作することは確認しておりました。もう少し調べてみると、Windowsキーを使うキーバインドの場合、次のようなパターンのものが動かないようです。
```
keymap_global["W-RS-m"] = "W-LS-m"
```
一方、Ctrlキーとの組み合わせの以下の設定（新規フォルダを作成する）は動きます。
```
keymap_global["C-RS-n"] = "C-LS-n"
```
Windowsの仕様のようですので、config.py で実現できる回避策を検討してみようかと思います。

\# L、Rを指定すればいいのですが、Fakeymacsを利用する上で、利用者に設定の条件（制約）を増やしたくないと考えているところでした。

**Comment by smzht** [comment]
本件、Windows の仕様によるもののようであり、Keyhac での対策は難しそうですので、クローズとさせていただきます。

確認いただき、ありがとうございました。

**Comment by crftwr** [comment]
@smzht , 
Windows の挙動に加え、Keyhacが内部でモディファイアキーの状態を遷移させる方法によるもののようです。

* L/Rを指定していないModifierキーは、Left側が指定されたとして処理する
* RShiftがすでに押されているとしても、LShiftを使ったキー操作をするために、LShift押す→RShift離す→Mキー押す→RShift押す→LShift離す、のような架空のキー操作を発行する。

この、モディファイアキーの押し直しが、Windowsキーの振る舞いと相性が悪いようです。
Keyhacがここを賢く、Shiftキーの押し直しが不要だと判断できるなら、この問題は起きないだろうと思いますが、現状はそうなってません。

**Comment by smzht** [comment]
調査いただき、ありがとうございます。
以下の対応が簡単ではあるのですが、あんまりかなぁと思っておりました。
```
keymap.replaceKey("RShift", "LShift")
```
一応、Fakeymacs の方は力ずくで対応をし、なんとかなりそうな目処が立ちました。
後ほど、差分コードをアップしたいと思います。公開するのは恥ずかしいところもありますが..。

**Comment by smzht** [comment]
InputKeyCommand のラッパー関数内で、RShift が押されていたときの処理を追加しました。
- https://github.com/smzht/fakeymacs/blob/0778be3044a9265eedd52b9dd664583c85367771/config.py#L1773-L1781

Keyhac のコードをちゃんと理解せずに、いろいろ内部関数を使いまわしており、お恥ずかしい限りです。
まずは、これでしばらく使ってみたいと思います。
