### ISSUE TITLE
実行中のアプリ

### ISSUE THREAD

**Issue by baron-tommy** [crftwr/keyhac-win#5]
# mac版のkeyhacについて質問があります。

下記のコードを実行し`hoge`に実行中のアプリ名をセットしたのですが、
エラーになります。  
※windows版だと動作しています。

``` python
def set_app_name(app_name):
    hoge = app_name.getProcessName()

keymap.defineWindowKeymap(check_func=set_app_name)
```

**Comment by crftwr** [comment]
レポートありがとうございます。

Mac版だと、check_funcに渡した関数の引数には、pyautoのWindowオブジェクトではなくて、accessibilityライブラリのApplicationオブジェクトが渡ってきます。

ドキュメントは、正しく更新されておらず、Windowsの説明のままになってしまっていますので、更新しないといけないですね。

**Comment by baron-tommy** [comment]
[こちら](https://github.com/atheriel/accessibility/blob/master/examples/appinfo.py)を参考にしています
app['AXTitle']は取得できたのですが、実行中のアプリ情報が取得できませんでした。  
keyhacの端末に表示している、アプリ情報の取得の仕方を教えて下さい。

``` python
def set_app_name(app_name):
    hoge = app_name[???]

    print(hoge) # 実行中のアプリ名 com.apple.Terminal


keymap.defineWindowKeymap(check_func=set_app_name)
```

**Comment by crftwr** [comment]
アプリ名は accessibility API だけでは取得できないため、下のようにしています。

ckit.getApplicationNameByPid(focus.pid)

https://github.com/crftwr/keyhac/blob/mac_port/keyhac_keymap.py#L1164

**Comment by baron-tommy** [comment]
解決しました
ありがとうございます。

win版とmac版両方利用させてもらっています。
素晴らしいソフトありがとうございます。

**Comment by crftwr** [comment]
解決したようでよかったです。
ドキュメントについては更新しておきます。
