### ISSUE TITLE
mac版のkeyhac VK_ について

### ISSUE THREAD

**Issue by baron-tommy** [crftwr/keyhac-win#6]
###### 下記の設定の場合動作しないキーがあります。

``` python
keymap_global['D-' + str(VK_A)] = hoge(VK_A)
```
###### 動作しないリスト

※間違えてたらすみません  
※aからzまでしか試していませんが、下記以外は動作しました。

```
asdfg
zxcv
```

VK_ の記述はサポート外でしょうか？
よろしくお願いします。

**Comment by crftwr** [comment]
keymap_global['D-' + str(VK_A)] = hoge(VK_A)
は、下の文と同じ意味です。
keymap_global['D-0'] = hoge(0)

"D-0" は、Aキーではなく、0キーの意味になります。

Aキーを意味するためには、 "D-A" とするか、"D-(0)" のように記述する必要があります。
仮想キーコードを文字列の表記の中で使う場合は、カッコでくくる必要がある点についてご注意ください。

**Comment by baron-tommy** [comment]
失礼しました
記述方式のミスですね

ありがとうございます。
