### ISSUE TITLE
修正要望

### ISSUE THREAD

**Issue by geotrader** [crftwr/keyhac-win#8]
間違っているかもしれませんが･･･

User0がワンショットモディファイアに設定できないような気がします.
デフォルトで入っているconfig.pyのkeymap_globalを定義するコード次の行に以下のコードを追加しただけです.
        keymap_global[ "O-User0" ] = "F7"
        このコードでは動きます.→keymap_global[ "O-LCtrl" ] = "F7"

後ワンショットモディファイアを二連打でクリップボードを呼び出す設定を,別フリーソフトでやっていたので再現しようとしましたが上手く行きませんでした.
multistrokekeymapに指定した組合せは実現できないのでしょうか.

```
    keymap_global[ "O-Alt" ] = keymap.defineMultiStrokeKeymap( "O-Alt" )
    keymap_global[ "O-Alt" ][ "O-Alt" ] = keymap.command_ClipboardList 
```

**Comment by crftwr** [comment]
defineModifierで定義したユーザモディファイアキーは、”User0-Space” のように使うことはできますが、”Alt-User0”のように、メインのキーを記述するために使うことはできません。代わりに、defineModifierのときに使った、割り当て元のキーを使う必要があります。

**Comment by crftwr** [comment]
Altキーの2回押しは、下のように、LAｌｔと、左Altキーであることを明示すれば可能です。

keymap_global[ "O-LAlt" ] = keymap.defineMultiStrokeKeymap( "O-LAlt" )
keymap_global[ "O-LAlt" ][ "O-LAlt" ] = keymap.command_ClipboardList

**Comment by geotrader** [comment]
一つ目の事項について書き方が悪く誤解を招いてしまっていると思いますので､
少し長いですが書き直します.

無変換の位置にuser0を割当して修飾キーのように使いたいと思っています.
一方で単純に単独でuser0を押した場合には無変換相当(F7)の機能を持たせたいのです.

ドキュメントを見るとそれを実現する記述があったので

---

ワンショットモディファイアとは、Ctrl や Shift、User0 など
    keymap_global[ "O-LCtrl" ] = command_Test
このように、 O- という修飾子を使用することで、ワンショットモディファイアを設定

---

とりあえずvimの動きとカタカナ変換を両立させるために以下の様に書いてみました.
    keymap.defineModifier( 29, "User0" )

```
    keymap_global[ "O-U0" ] = "F7"
    keymap_global[ "U0-h" ] = "Left"
    keymap_global[ "U0-j" ] = "Down"
    keymap_global[ "U0-k" ] = "Up"
    keymap_global[ "U0-l" ] = "Right"
```

ところが
"ERROR : キーの表記が正しくありません : O-U0"
というエラーを返されまして動きません.

よろしくお願いします.

**Comment by crftwr** [comment]
その場合は、"O-(29)"と記述します。User0をメインキーとして記述することはできません。

**Comment by geotrader** [comment]
すみません.やっと意味が分かりました.
本当に素早い解答ありがとうございました.
